import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { FinanceAnalyticsSummary, FinanceOverview, FinanceTrendPoint } from "@/lib/finance-insights";
import { formatFinanceCurrency } from "@/lib/finance-insights";
import { EXPENSE_CATEGORY_LABELS } from "@/lib/finance-types";

export async function generateFinanceReportPdf(args: {
  title: string;
  overview: FinanceOverview;
  analytics: FinanceAnalyticsSummary;
  generatedAt: string;
}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const pageWidth = 595.28;
  const pageHeight = 841.89;
  const margin = 48;
  let page = pdf.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  function ensureSpace(required: number) {
    if (y < margin + required) {
      page = pdf.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
  }

  function drawHeading(text: string) {
    ensureSpace(24);
    page.drawText(text, { x: margin, y, size: 14, font: bold, color: rgb(0.08, 0.1, 0.14) });
    y -= 22;
  }

  function drawLine(text: string, size = 10) {
    ensureSpace(16);
    page.drawText(text, { x: margin, y, size, font: regular, color: rgb(0.2, 0.22, 0.26) });
    y -= 14;
  }

  page.drawText(args.title, { x: margin, y, size: 18, font: bold, color: rgb(0.04, 0.1, 0.23) });
  y -= 24;
  drawLine(`Generated ${new Date(args.generatedAt).toLocaleString("en-GB")}`, 9);
  y -= 8;

  drawHeading("Profit and loss summary");
  drawLine(`Income this month: ${formatFinanceCurrency(args.overview.incomeThisMonth)}`);
  drawLine(`Expenses this month: ${formatFinanceCurrency(args.overview.expensesThisMonth)}`);
  drawLine(`Net profit this month: ${formatFinanceCurrency(args.overview.profitThisMonth)}`);
  drawLine(`Year-to-date profit: ${formatFinanceCurrency(args.overview.netProfitYtd)}`);
  drawLine(`Rolling 12-month profit: ${formatFinanceCurrency(args.overview.rollingTwelveMonthProfit)}`);
  y -= 8;

  drawHeading("Income breakdown");
  drawLine(`Bookings: ${formatFinanceCurrency(args.analytics.incomeBreakdown.bookings)}`);
  drawLine(`Subscriptions: ${formatFinanceCurrency(args.analytics.incomeBreakdown.subscriptions)}`);
  drawLine(`Camps: ${formatFinanceCurrency(args.analytics.incomeBreakdown.camps)}`);
  y -= 8;

  drawHeading("Expense breakdown");
  if (args.analytics.expenseBreakdown.length === 0) {
    drawLine("No expenses recorded yet.");
  } else {
    for (const item of args.analytics.expenseBreakdown) {
      drawLine(`${EXPENSE_CATEGORY_LABELS[item.category]}: ${formatFinanceCurrency(item.total)}`);
    }
  }
  y -= 8;

  drawHeading("Monthly trend");
  for (const point of args.analytics.incomeSeries) {
    drawLine(
      `${point.label}: income ${formatFinanceCurrency(point.income)}, expenses ${formatFinanceCurrency(point.expenses)}, profit ${formatFinanceCurrency(point.profit)}`,
    );
  }
  y -= 8;

  drawHeading("Coach payroll summary");
  drawLine(`Outstanding: ${formatFinanceCurrency(args.analytics.payrollSummary.outstanding)}`);
  drawLine(`Paid: ${formatFinanceCurrency(args.analytics.payrollSummary.paid)}`);
  y -= 8;

  if (args.analytics.campProfitability.length > 0) {
    drawHeading("Camp profitability");
    for (const camp of args.analytics.campProfitability.slice(0, 8)) {
      drawLine(
        `${camp.campName}: revenue ${formatFinanceCurrency(camp.revenue)}, expenses ${formatFinanceCurrency(camp.expenses)}, profit ${formatFinanceCurrency(camp.profit)}`,
      );
    }
  }

  ensureSpace(20);
  page.drawText("Generated by Awarix Finance Centre", {
    x: margin,
    y: margin - 8,
    size: 8,
    font: regular,
    color: rgb(0.5, 0.5, 0.5),
  });

  return pdf.save();
}

export function getFinanceReportFilename(title: string): string {
  const safe = title.trim().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-").toLowerCase();
  return `${safe || "finance-report"}.pdf`;
}

export type FinanceReportChartData = {
  trend: FinanceTrendPoint[];
};
