import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFPage,
} from "pdf-lib";
import { getPositionSummary, type PlayerPositionOption, type PreferredFootOption } from "@/lib/player-profile";

type ReportPdfInput = {
  playerName: string;
  preferredFoot?: PreferredFootOption;
  primaryPosition?: PlayerPositionOption | null;
  secondaryPositions?: PlayerPositionOption[];
  teamNames?: string[];
  report: string;
  date?: Date;
};

const A4 = {
  width: 595.28,
  height: 841.89,
};

const margin = 56;
const footerText =
  "Generated by CoachFlow – The AI-powered operating system for football coaches.";

function slugifyFilename(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

function formatIsoDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

function formatDisplayDate(date: Date): string {
  return new Intl.DateTimeFormat("en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(date);
}

function wrapLine(
  text: string,
  font: PDFFont,
  fontSize: number,
  maxWidth: number,
): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length === 0) return [""];

  const lines: string[] = [];
  let currentLine = "";

  for (const word of words) {
    const candidate = currentLine ? `${currentLine} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, fontSize) <= maxWidth) {
      currentLine = candidate;
      continue;
    }

    if (currentLine) lines.push(currentLine);

    if (font.widthOfTextAtSize(word, fontSize) <= maxWidth) {
      currentLine = word;
      continue;
    }

    let fragment = "";
    for (const char of word) {
      const candidateFragment = `${fragment}${char}`;
      if (font.widthOfTextAtSize(candidateFragment, fontSize) <= maxWidth) {
        fragment = candidateFragment;
      } else {
        if (fragment) lines.push(fragment);
        fragment = char;
      }
    }
    currentLine = fragment;
  }

  if (currentLine) lines.push(currentLine);
  return lines;
}

function wrapText(
  text: string,
  font: PDFFont,
  fontSize: number,
  maxWidth: number,
): string[] {
  return text
    .split(/\n/)
    .flatMap((line) =>
      line.trim()
        ? wrapLine(line.trim(), font, fontSize, maxWidth)
        : [""],
    );
}

function drawFooter(page: PDFPage, font: PDFFont, pageNumber: number) {
  page.drawLine({
    start: { x: margin, y: 54 },
    end: { x: A4.width - margin, y: 54 },
    thickness: 0.5,
    color: rgb(0.86, 0.88, 0.91),
  });
  page.drawText(footerText, {
    x: margin,
    y: 34,
    size: 8.5,
    font,
    color: rgb(0.38, 0.43, 0.5),
  });
  page.drawText(String(pageNumber), {
    x: A4.width - margin - 10,
    y: 34,
    size: 8.5,
    font,
    color: rgb(0.38, 0.43, 0.5),
  });
}

export function getReportPdfFilename(playerName: string, date = new Date()) {
  const safePlayerName = slugifyFilename(playerName) || "player";
  return `coachflow-report-${safePlayerName}-${formatIsoDate(date)}.pdf`;
}

export async function generateReportPdf({
  playerName,
  preferredFoot = "Unknown",
  primaryPosition = null,
  secondaryPositions = [],
  teamNames = [],
  report,
  date = new Date(),
}: ReportPdfInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const regularFont = await pdf.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  const italicFont = await pdf.embedFont(StandardFonts.HelveticaOblique);

  const logoResponse = await fetch("/logo.png");
  if (!logoResponse.ok) {
    throw new Error("Could not load CoachFlow logo for PDF export.");
  }
  const logoImage = await pdf.embedPng(await logoResponse.arrayBuffer());
  const logoDims = logoImage.scale(0.18);

  let page = pdf.addPage([A4.width, A4.height]);
  let y = A4.height - margin;

  page.drawImage(logoImage, {
    x: margin,
    y: y - logoDims.height,
    width: logoDims.width,
    height: logoDims.height,
  });

  y -= logoDims.height + 34;

  page.drawText("Progress Report", {
    x: margin,
    y,
    size: 28,
    font: boldFont,
    color: rgb(0.04, 0.1, 0.23),
  });

  y -= 32;
  page.drawText(`Player: ${playerName}`, {
    x: margin,
    y,
    size: 12.5,
    font: boldFont,
    color: rgb(0.04, 0.1, 0.23),
  });

  y -= 20;
  page.drawText(formatDisplayDate(date), {
    x: margin,
    y,
    size: 10.5,
    font: regularFont,
    color: rgb(0.38, 0.43, 0.5),
  });

  y -= 18;
  page.drawText(
    `Profile: ${getPositionSummary({
      primary_position: primaryPosition,
      secondary_positions: secondaryPositions,
    })} · ${preferredFoot} foot`,
    {
      x: margin,
      y,
      size: 10.5,
      font: regularFont,
      color: rgb(0.38, 0.43, 0.5),
    },
  );

  if (teamNames.length > 0) {
    y -= 18;
    page.drawText(`Teams: ${teamNames.join(", ")}`, {
      x: margin,
      y,
      size: 10.5,
      font: regularFont,
      color: rgb(0.38, 0.43, 0.5),
    });
  }

  y -= 28;
  page.drawLine({
    start: { x: margin, y },
    end: { x: A4.width - margin, y },
    thickness: 1,
    color: rgb(0.06, 0.73, 0.51),
  });

  y -= 28;

  const maxTextWidth = A4.width - margin * 2;
  const reportLines = wrapText(report, regularFont, 11.5, maxTextWidth);
  const lineHeight = 17;
  const pageBottom = 82;

  for (const line of reportLines) {
    if (y < pageBottom + lineHeight) {
      page = pdf.addPage([A4.width, A4.height]);
      y = A4.height - margin;
    }

    if (line) {
      page.drawText(line, {
        x: margin,
        y,
        size: 11.5,
        font: regularFont,
        color: rgb(0.12, 0.16, 0.22),
      });
      y -= lineHeight;
    } else {
      y -= lineHeight * 0.75;
    }
  }

  y -= 20;
  if (y < pageBottom + 40) {
    page = pdf.addPage([A4.width, A4.height]);
    y = A4.height - margin;
  }

  page.drawText("Prepared with CoachFlow", {
    x: margin,
    y,
    size: 11,
    font: italicFont,
    color: rgb(0.06, 0.73, 0.51),
  });

  for (let index = 0; index < pdf.getPageCount(); index += 1) {
    drawFooter(pdf.getPages()[index], regularFont, index + 1);
  }

  return pdf.save();
}
