import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { PitchLayout, PitchElement } from "@/lib/training-types";
import { PITCH_ELEMENT_LABELS } from "@/lib/training-types";

export async function generatePitchPdf(args: {
  title: string;
  layout: PitchLayout;
}): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  page.drawText(args.title, { x: 40, y: 800, size: 16, font: bold, color: rgb(0.1, 0.1, 0.1) });
  page.drawText("Training pitch diagram", { x: 40, y: 780, size: 10, font, color: rgb(0.4, 0.4, 0.4) });

  const pitchX = 70;
  const pitchY = 180;
  const pitchW = 455;
  const pitchH = 560;

  page.drawRectangle({
    x: pitchX,
    y: pitchY,
    width: pitchW,
    height: pitchH,
    borderColor: rgb(0.2, 0.55, 0.3),
    borderWidth: 2,
    color: rgb(0.9, 0.96, 0.9),
  });
  page.drawLine({
    start: { x: pitchX + pitchW / 2, y: pitchY },
    end: { x: pitchX + pitchW / 2, y: pitchY + pitchH },
    thickness: 1,
    color: rgb(0.2, 0.55, 0.3),
  });

  for (const element of args.layout.elements) {
    drawPitchElement(page, element, pitchX, pitchY, pitchW, pitchH, font);
  }

  page.drawText("Generated by Awarix", {
    x: 40,
    y: 40,
    size: 9,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return pdf.save();
}

function drawPitchElement(
  page: ReturnType<PDFDocument["addPage"]>,
  element: PitchElement,
  pitchX: number,
  pitchY: number,
  pitchW: number,
  pitchH: number,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
) {
  const x = pitchX + (element.x / 100) * pitchW;
  const y = pitchY + pitchH - (element.y / 100) * pitchH;
  const label = element.label ?? PITCH_ELEMENT_LABELS[element.type].slice(0, 1);

  if (element.type === "zone") {
    page.drawRectangle({
      x: x - 20,
      y: y - 20,
      width: 40,
      height: 40,
      color: rgb(0.85, 0.95, 0.88),
      borderColor: rgb(0.2, 0.55, 0.3),
      borderWidth: 1,
    });
    return;
  }

  if (element.type === "arrow") {
    page.drawLine({
      start: { x, y },
      end: { x: x + 30, y: y + 10 },
      thickness: 2,
      color: rgb(0.15, 0.15, 0.15),
    });
    return;
  }

  page.drawCircle({
    x,
    y,
    size: element.type === "goal" ? 10 : 6,
    color:
      element.type === "player"
        ? rgb(0.1, 0.45, 0.85)
        : element.type === "cone"
          ? rgb(0.95, 0.45, 0.1)
          : rgb(0.2, 0.2, 0.2),
  });

  page.drawText(label, {
    x: x - 4,
    y: y - 3,
    size: 7,
    font,
    color: rgb(1, 1, 1),
  });
}

export function getPitchPdfFilename(title: string): string {
  const safe = title.trim().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-").toLowerCase();
  return `${safe || "training-pitch"}-diagram.pdf`;
}
